name: Update Veda-UI version

on:
  workflow_dispatch:
    inputs:
      VERSION_NUMBER:
        type: string
  repository_dispatch:
    types: [update-version]

permissions:
  contents: write
  pull-requests: write

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  makepr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: main
        fetch-depth: 0
    - name: Use Node.js ${{ env.NODE }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE }}

    - name: Set Version Variable
      id: set-version
      run: echo "VERSION=${{ github.event.client_payload.VERSION_NUMBER || inputs.VERSION_NUMBER }}" >> $GITHUB_ENV
  
    - name: git config
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: Update veda-ui version
      shell: bash
      run: |
        npm install teamimpact/veda-ui@${{ github.event.client_payload.VERSION_NUMBER }}
    - name: Create Pull Request
      id: making-pr
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: "Update veda-ui to ${{ github.event.client_payload.VERSION_NUMBER }}"
        title: "ci: Update veda-ui to version ${{ github.event.client_payload.VERSION_NUMBER }}"
        body: "This is an automatic PR that updates veda-ui dependency to version `${{ github.event.client_payload.VERSION_NUMBER }}`."
        base: main
        branch: ci-update-vedaui-${{ github.event.client_payload.VERSION_NUMBER }}
    - name: Notify veda-ui update through Slack
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload: |
          text: "*veda-ui library bump ${{ env.VERSION }}*: ${{ job.status }}\n Preview link: ${{ steps.making-pr.outputs.pull-request-url }}"
          blocks:
            - type: "section"
              text:
                type: "mrkdwn"
                text:  "*veda-ui library bump ${{ env.VERSION }}*: ${{ job.status }}\n Preview link: ${{ steps.making-pr.outputs.pull-request-url }}"